version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
      - beat

  redis:
    image: "redis:alpine"

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A celery_beat beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis